spring:
  redis:
    host: 192.168.5.137
    port: 6379
    password: 1234
    lettuce:
      pool:
        min-idle: 1
        max-idle: 10
        max-active: 10
        time-between-eviction-runs: 10s
  cloud:
    gateway:
      httpclient:
        pool:
          max-idle-time: 3600000
      redis-route-definition-repository:
        enabled: true

dubbo:
  application:
    name: dubbo-springboot-consumer
  registry:
    address: zookeeper://192.168.5.137:2181